const testDrivers = [
  "İsmail Safa Özler",
  "Mehmet Kusun",
  "Zamir Damar Arıkoğlu",
  "Ahmet Besim Atalay",
  "Vehbi Çorakçı",
  "Mehmet Neşet Özercan",
  "Ali Rıza Özdarende",
  "Ahmet Esat Uras",
  "Mehmet Nafiz Aktin",
  "Osmanbey Selmen",
  "Mustafa Kemal Atatürk",
  "Ali Fuat Cebesoy",
  "Ali Kütükçüoğlu",
  "Mustafa Hilmi Çayırlıoğlu",
  "İhsan Pehlivanlı",
  "Ömer Mümtaz Tambi",
  "Şakir Kınacı",
  "Ahmet Saki Derin",
  "Hasan Pırıltı",
  "Mahmut Murat Şerefli",
  "Rasih Kaplan",
  "Halit Karsıalan",
  "Hasan Tahsin Uzer",
  "Talat Sönmez",
  "Hilmi Gür",
  "İzzettin Çalışlar",
  "Mazhar Germen",
  "Mithat Aydın",
  "Reşit Galip",
  "Hasan Tahsin San",
  "Zekai Apaydın",
  "Süleyman Sudi Acarbay",
  "Şefik Baydar",
  "Mehmet Dinç",
  "Samih Yalnızgil",
  "Mehmet Şükrü Yaşin",
  "Muhittin Başay",
  "Sofrasur Asizade Resul Bey",
  "Cevat Abbas Gürer",
  "Emin Cemal Suda",
  "Falih Rıfkı Atay",
  "Mehmet Şükrü Gülez",
  "Mehmet Nuhoğlu",
  "Ahmet Hamdi Altıok",
  "Mehmet Avni Doğan",
  "Salih Bozok",
  "Süleyman Sırrı İçöz",
  "Hüseyin Çelikbaş",
  "Mustafa Şeref Özkan",
  "Ali Hikmet Ayerdem",
  "Mustafa Fehmi Gerçeker",
  "Necati Kurtuluş",
  "Sakallı Nurettin",
  "Osman Nuri Özpay",
  "Hasan Refet Canıtez",
  "Cavit Paşa",
  "Süleyman Necmi Selmen",
  "Talat Özüdoğru",
  "Hüseyin Avni Zaimler",
  "İhsan Eryavuz",
  "Şakir Kesebir",
  "Hüseyin Ferit Törümküney",
  "İsmail Kemal Alpsar",
  "İsmet Eker",
  "Mehmet Münir Çağıl",
  "Ahmet Ziya Tonguç",
  "Mustafa Cantekin",
  "Kazım Samanlı",
  "Ali Haydar Öktem",
  "Mazhar Müfit Kansu",
  "Necip Ali Küçüka",
  "Yusuf Başkaya",
  "Ahmet Şükrü Kulualp",
  "Feridun Fikri Düşünsel",
  "Cavit Ekin",
  "Feyzi Pirinççioğlu",
  "İbrahim Talî Öngören",
  "Mehmet Nuri Budak",
  "Abdurrahman Şeref Uluğ",
  "Ziya Gökalp",
  "Mehmet Zülfü Tigrel",
  "Cafer Tayyar Eğilmez",
  "Faik Kaltakkıran",
  "Hüseyin Rıfkı Bey",
  "İsmail Cevat Çobanlı",
  "Hüseyin Gökçelik",
  "Muhittin Çöteli",
  "Mustafa Solmaz",
  "Mehmet Naci Karaali",
  "Süleyman Karakaya",
  "İhsan Sağlam",
  "İhsan Hamit Tiğrel",
  "Kâzim Bey (Oral)",
  "Ahmet İffet Mercimekoğlu",
  "Fikret Onuralp",
  "Halil Işık",
  "İbrahim Çolak",
  "Rasim Celalettin Öztekin",
  "Abdülhak Fırat",
  "Mehmet Hamdi Arpağ",
  "Mehmet Sabit Sağıroğlu",
  "Bahri Sarıtepe",
  "Mehmet Cazım Duru",
  "Halet Sağıroğlu",
  "Münir Hüsrev Göle",
  "Raif Dinç",
  "Rüştü Paşa",
  "Ziyaeddin Gözübüyük",
  "Abdullah Azmi Torun",
  "Ali Ulvi Bayrakdar",
  "Mehmet Arif Bey",
  "Emin Sazak",
  "Remzi Güres",
  "Ali Cenani",
  "Mustafa Ferit Arsan",
  "Ali Kılıç",
  "Hafız Mehmet Şahin",
  "Celal Nuri İleri",
  "Ali Haydar Bey",
  "Muhittin Temoçin",
  "Hacim Muhittin Çarıklı",
  "Hakkı Tarık Us",
  "Musa Kazım Okay",
  "Ali Şevket Çolak",
  "Tahir Karadeniz",
  "Cemal Hüsnü Taray",
  "Hasan Fehmi Ataç",
  "Veysel Rıza Zarbun",
  "Zeki Kadirbeyoğlu",
  "Asaf Süleyman Doras",
  "Mehmet Nazmi Dilaveroğlu",
  "Hüseyin Hüsnü Özdamar",
  "Hafız İbrahim Demiralay",
  "Ahmed Mükerrem Karaağaç",
  "Hafız Emin İnankur",
  "Tevfik Marlalı",
  "Abdurrahman Şeref",
  "Abdülhak Adnan Adıvar",
  "Ahmet Hamdi Denizmen",
  "Ahmet Muhtar Mollaoğlu",
  "Ali Rıza Bebek",
  "Behiç Erkin",
  "Edip Servet Tör",
  "Refet Bele",
  "Fevzi Çakmak",
  "Tevfik Kamil Koperler",
  "Fuat Ağralı",
  "İsmail Hakkı Erel",
  "Hamdullah Suphi Tanrıöver",
  "Ali Haydar Yuluğ",
  "Hüseyin Rauf Orbay",
  "İhsan Sökmen",
  "İsmail Canbulat",
  "Musa Kâzım Karabekir",
  "Ali Fethi Okyar",
  "Refik Saydam",
  "Süleyman Sırrı Aral",
  "Yusuf Akçora",
  "Ziya Karamürsel",
  "Fahrettin Altay",
  "Mustafa Kamil Dursun",
  "Celâl Bayar",
  "Mahmut Esat Bozkurt",
  "Mustafa Necati Uğural",
  "Mustafa Rahmi Köken",
  "Ahmet Münir Akkaya",
  "Ahmet Hamdi Aksoy",
  "Şükrü Saracoğlu",
  "Tevfik Rüştü Aras",
  "Seyit Bey",
  "Ahmet Talat Onay",
  "Yusuf Ziya İsfendiyaroğlu",
  "Binbaşızade Rıza Bey",
  "Ali Sururi Tönük",
  "İsmail Sabuncu",
  "Mehmet Emin Yurdakul",
  "Ahmet Süreyya Örgeevren",
  "Şuuri Hoşafcı",
  "Haydar Adil Müsteçaplıoğlu",
  "Abdullah Hulusi Zarplı",
  "Kâzım Özalp",
  "Mehmet Emir",
  "Mehmet Vehbi Bolak",
  "Osman Niyazi Burcu",
  "Ahmet Ağaoğlu",
  "Ömer Tarım",
  "Ahmet Mahir Efendi",
  "Ali Nazmi Özügür",
  "Ali Rıza Bey",
  "Halit Akmansü",
  "Hasan Fehmi Tümerkan",
  "Mehmet Mühto",
  "Mehmet Necmettin Kocataş",
  "Veled Çelebi İzbudak",
  "Ahmet Hilmi Kalaç",
  "Halit Mazhar Karakaya",
  "Nuh Naci Yazgan",
  "Sabit Gözügeçgel",
  "Ahmet Zeki Karakimseliler",
  "Fuat Umay",
  "Şevket Ödül",
  "Şükrü Naili Gökberk",
  "Ali Rıza Benli",
  "Lütfi Müfit Özdeş",
  "Mahbub Erdoğru",
  "Mehmed Refik Kakmacı",
  "Yahya Galip Kargı",
  "Ahmet Şükrü Bey",
  "İbrahim Hakkı Tolon",
  "İbrahim Süreyya Yiğit",
  "Mustafa Kerem",
  "Mehmet Ragıp Akça",
  "Saffet Arıkan",
  "Eyüp Sabri Hayırlıoğlu",
  "Fuat Gökbudak",
  "Hacı Bekir Sümer",
  "Halil İbrahim Nakıpoğlu",
  "Musa Kazım Onar",
  "Mustafa Ulusan",
  "Mustafa Feyzi Karaağaç",
  "Mehmet Naim Onat",
  "Refik Koraltan",
  "Tevfik Fikret Sılay",
  "Ali Saip Ursavaş",
  "Ali Şadi Çelik",
  "Ahmet Ferit Tek",
  "Cevdet Barlas",
  "Mahmut Faik Soylu",
  "Mehmet Nuri Conker",
  "Ragıp Soysal",
  "Recep Peker",
  "Mehmet Rıza Dinçay",
  "Seyfi Aydın",
  "İsmet İnönü",
  "Hilmi Oytaç",
  "Hacı Bedir Fırat",
  "Mahmut Nedim Zabcı",
  "Reşit Ağar",
  "Abdülkadir Emirmahmutoğlu",
  "Mehmet Erten",
  "Mehmet Mithat Alan",
  "Mehmet Nurettin Akkın",
  "Mehmet Tahsin Hüdayioğlu",
  "Abdülgani Ensari",
  "Abdürrezzak Şatana",
  "Ali Rıza Erten",
  "Derviş Ural",
  "Mehmet Necip Güven",
  "Yakup Kadri Karaosmanoğlu",
  "Mehmet Esat İleri",
  "Şükrü Kaya",
  "Yunus Nadi Abalıoğlu",
  "Ahmet Besim Özek",
  "Mehmet Niyazi Ramazanoğlu",
  "İlyas Sami Muş",
  "Osman Kadri Bingöl",
  "Rıza Kotan",
  "Ata Atalay",
  "Ebubekir Hâzım Tepeyran",
  "Ali Galip Yenen",
  "Halit Hami Mengi",
  "Ahmet Faik Günday",
  "Halil Sıtkı Kumru",
  "Ahmet Hamdi Yalman",
  "İsmail Çamaş",
  "Mehmet Recai Baykal",
  "Ali Zırh",
  "Ekrem Rize",
  "Esat Özoğuz",
  "Ahmet Fuat Bulca",
  "Hasan Cavit Belül",
  "Rauf Benli",
  "Abidin Bey",
  "Ethem Büke",
  "Kemal Gürol",
  "Mehmet Sabri Toprak",
  "Mustafa Fevzi Sarhan",
  "Mehmet Nafiz Dumlu",
  "Reşat Kayalı",
  "Saim Uzel",
  "Hüseyin Vasıf Çınar",
  "Mehmet Yaşar Özey",
  "Halil Hulki Ayrım",
  "Mahmut Nedim Soydan",
  "Kemalettin Sami Gökçen",
  "Recep Zühtü Soyak",
  "Rıza Nur",
  "Yusuf Kemal Tengirşenk",
  "Mehmet Halis Tarıkahya",
  "Muammer Bey",
  "Ömer Şevki Purut",
  "Abdürrahman Rahmi Katoğlu",
  "Rasim Başara",
  "Şemsettin Günaltay",
  "Yusuf Ziya Başara",
  "Cudi Paşa",
  "Halil Fahri Gürmen",
  "Abdulkadir Kadri Kürkcü",
  "Mahmut Odabaşı",
  "Faik Öztrak",
  "Mehmet Cemil Uybadın",
  "Bekir Sami Kunduh",
  "Mehmet Emin Bayav",
  "Kamil Baştopçu",
  "Mustafa Sabri Süsoy",
  "Abdullah Okyay",
  "Ahmet Muhtar Cilli",
  "Hasan Saka",
  "Ahmet Hamdi Ülkümen",
  "Mehmet Rahmi Eyüboğlu",
  "Süleyman Sırrı Gedik",
  "Ali Şefik Başman",
  "Ali Fuat Bucak",
  "Hüsrev Gerede",
  "Mehmet Refet Ülgen",
  "Refet Topçuoğlu",
  "Saffet Kemalettin Yetkin",
  "Yahya Kemal Beyatlı",
  "Hakkı Ungan",
  "İbrahim Arvas",
  "Münip Boya",
  "Halil Türkmen",
  "Ahmet Ragıp Özdemiroğlu",
  "Tunalı Hilmi",
  "Yusuf Ziya Özenci",
];
const drivers = {
  'GET /api/drivers': testDrivers,
};
module.exports = { drivers, testDrivers };
